# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "TheAlphaZone"
email: "ang096@e.ntu.edu.sg"  # Added from old config author section
description: >- # this means to ignore newlines until "baseurl:"
  Computer Science student exploring Data Structures and Artificial Intelligence.
twitter_username: "your_twitter"  # Replace with your Twitter handle if applicable
github_username: "AlphaeusNg"
minimal_mistakes_skin: "sunrise"  # Updated from old config
search: true
locale: "en-US"  # Added from old config
title_separator: " - "  # Added from old config
subtitle: "by Alphaeus"  # Added from old config
name: "Alphaeus"  # Added from old config
url: "https://alphaeusng.github.io"  # Update if your site URL has changed
baseurl: ""  # Update if your site is in a subdirectory
repository: "AlphaeusNg/minimal-mistakes"  # Update to your new repository
words_per_minute: 200  # Added from old config

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Asia/Singapore"  # Added from old config; adjust if needed

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Alphaeus Ng"
  avatar: "/assets/picture of myself.jpg"  # Update path to your avatar image
  bio: "Pursuing truthteste."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlphaeusNg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alphaeus-ng-3a30b1188/"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/18020911/turq6ise"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/turq6ise/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ang096@e.ntu.edu.sg"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlphaeusNg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alphaeus-ng-3a30b1188/"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/18020911/turq6ise"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/turq6ise/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ang096@e.ntu.edu.sg"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false  # Set to true if you configure a comments provider
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/